### ISSUE TITLE
How much accuracy your algorithm got?

### ISSUE THREAD

**Issue by sainimohit23** [ajinkyaT/AxisBank_AI_Challenge#1]

**Comment by ajinkyaT** [comment]
Accuracy wasn't the metric here, the contrastive loss was used which got converged to good extend after training (see figure in [final_axis_fake_signature_verification.ipynb](https://github.com/ajinkyaT/AxisBank_AI_Challenge/blob/master/Forged_Signature_Verification/final_axis_fake_signature_verification.ipynb) notebook)
